settings:
  tnt:
    test: # Значение должно быть уникальным
      breakObsidian: false # Может ли динамит взрывать обсидиан
      radiusExplosion: 3 # Радиус XxYxZ на котором будет взрывать блоки динамит
      breakRegions: false # Может ли данный динамит взрывать блоки регионов (Без учёта прочности)
      breakBlocksInWater: false # Может ли динамит взрываться в воде
      breakSpawners: false # Может ли динамит взрывать спавнеры (Они будут выпадать)
      breakSpawnersInRegion: true # Может ли динамит взрывать спавнеры в регионах (Они будут выпадать)
      explosionInterval: 5 # Время в секундах, через которое динамит взорвется
      breakUnbreakableRegions: true # Может ли данный динамит взрывать нерашунимые регионы
      break-regions: # Список регионов, которые динамит сможет ломать (Без учёта прочности). Указывать ключ блока привата из CultAnarchyRegions
        - ''
      autoIgnite: true # Будет ли динамит сразу поджигаться
      gravity: true # Не будет ли воздействовать на динамит гравитация
      meta: # Мета данные предмета
        glow: true # Будет ли динамит подсвеченым
        customModelData: 0
        displayName: "&c&lСупер ТНТ" # Отображаемое название
        lore: {} # Описание предмета
